name: Build (run tests and check style)

on:
  push: {}
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "yarn"
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: yarn check-lint
      - run: yarn check-prettier
